model:
  base_learning_rate: 4.5e-6
  target: ldm.models.firststagemodel.FirstStageModel
  params:
    monitor: "val/rec_loss"
    lossconfig:
      target: ldm.modules.losses.EncoderLoss
      params: {}

    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    liifconfig:
      hidden_list: [256, 256, 256, 256]
      cell_decode: True
      local_ensemble: True

    trainconfig:
      image_key: image_hr
      gt_min: 64
      gt_max: 256

    valconfig:
      image_key: image_hr
      gt_min: 256
      gt_max: 256


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    wrap: True
    train:
      target: ldm.data.datasets.FFHQ
      params:
        size: 256
    validation:
      target: ldm.data.datasets.FFHQ
      params:
        size: 256
        first_k: 100

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 4
        increase_log_steps: False
        log_first_step: True
        log_all_val: True

  trainer:
    benchmark: True