model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm.SRDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    log_every_t: 100
    timesteps: 1000
    loss_type: l2
    first_stage_key: image_hr
    cond_stage_key: image_lr
    image_size: 48
    channels: 3
    inp_size: 192
    default_output_size: 192
    c_encode: True
    conditioning_key: concat
    concat_mode: True
    cond_stage_trainable: False
    monitor: val/loss_simple_ema
    scale_by_std: True
    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 48
        in_channels: 6
        out_channels: 3
        model_channels: 160
        attention_resolutions: [12, 6]
        num_res_blocks: 2
        channel_mult: [1, 2, 2, 4]
        num_head_channels: 32
        
    first_stage_config:
      target: ldm.models.firststagemodel.FirstStageModel
      params:
        ckpt_path: # first_stage_model checkpoint
        lossconfig:
          target: torch.nn.Identity

        ddconfig:
          double_z: False
          z_channels: 3
          resolution: 192
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0

        liifconfig:
          hidden_list: [256, 256, 256, 256]
          cell_decode: True
          local_ensemble: True

    cond_stage_config:
      target: torch.nn.Identity

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    wrap: True
    train:
      target: ldm.data.datasets.DF2KTrain
      params:
        size: 192
        lr_size: 48
    validation:
      target: ldm.data.datasets.DIV2KValidation
      params:
        size: 192
        lr_size: 48
        first_k: 100

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 3000
        max_images: 4
        increase_log_steps: False
        log_first_step: True
        log_images_kwargs:
          plot_denoise_rows: True

  trainer:
    benchmark: True